apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-arov
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-arov@sha256:1c4c4adac5cbcad2a03ac8086aeae5a699fb8229b181aa223839fc0228f9c73b
        name: my-nodejs
        resources: {}
status: {}
